### ISSUE TITLE
ESP32-C3 gives me a compile error

### ISSUE THREAD

**Issue by fa-yoshinobu** [TcMenu/IoAbstraction#197]
I get the following error and cannot compile

.pio/libdeps/seeed_xiao_esp32c3/IoAbstraction/src/esp32/ESP32AnalogDevice.cpp:14:10: fatal error: driver/dac.h: No such file or directory
 #include <driver/dac.h>
          ^~~~~~~~~~~~~~

I think the cause is the same as here
https://github.com/davetcc/IoAbstraction/issues/161

I changed #ifndef CONFIG_IDF_TARGET_ESP32S3 to CONFIG_IDF_TARGET_ESP32C3 in ESP32AnalogDevice.cpp and the compilation was successful and tcMenu works.

Operation confirmed with Seeed Studio XIAO ESP32C3

**Comment by davetcc** [comment]
Fixed by PR to use include check instead of looking for flags.

**Comment by tookitogo** [comment]
Checking for the include breaks -S3 support: Espressif's ESP32-S3 dev board definition _does_ include `dac.h`, so this check now causes compile errors because it is setting `ESP_HAS_DAC` on a board that does not actually have one. 

There is already a macro for this capability. Just test for the `SOC_DAC_SUPPORTED` macro, one of many capabilites that Espressif has macros for: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/soc_caps.html (Which does state the caveat that "Please note that the contents of soc/soc_caps.h are currently unstable and may undergo significant changes in the future.")

The following test succeeds (in that it correctly prints "not defined" on an S3) in Arduino IDE:
```
#ifdef SOC_DAC_SUPPORTED
  #pragma message "SOC_DAC_SUPPORTED is defined"
#else
  #pragma message "SOC_DAC_SUPPORTED is NOT defined"
#endif
```

**Comment by davetcc** [comment]
Thanks for this. I’m presently finalising release 5.0. This is a very low risk change so I’ll try and include it.

Further to this, longer term, I now have an ESP32C3 board for testing. I’ll be setting it up with a menu shortly, then I’ll have dev kits for ESP32, ESP32s2, ESP32s3 and ESP32c3. Mix of With and without SRAM.

**Comment by davetcc** [comment]
> Which does state the caveat that … may undergo significant changes in the future.

Yep, adds to the enjoyment of having a relatively low level library like this. Will just have to track it best we can.
